spring:
  application:
    name: synk-web

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile


  logging:
    level:
      root: INFO
      com.synk.backend: DEBUG
server:
  port: ${PORT}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_LIFESPAN}



#app:
#  frontend:
#    url: ${FRONTEND_URL}
#  backend:
#    base-url: ${BACKEND_URL}
